version: '3.5'
services:
  rule-engine:
    container_name: rule-engine
    environment:
      org.asynchttpclient.readTimeout: 150000
      org.asynchttpclient.requestTimeout: 150000
      spring.redis.host: redis
      spring.redis.port: 6379
      spring.redis.password: youshallnotpass9
      spring.redis.database: 2
      jumei.auth.api.addr: http://43.135.220.141:8301/auth
      spring.datasource.url: jdbc:mysql://mysql57:3306/re?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&autoReconnect=true
      spring.datasource.username: root
      spring.datasource.password: 777888OP
      jumei.auth.api.app.key: e9d34b22cdcd11e78d73842b2b738d12
    image: adoptopenjdk/openjdk8
    ports:
      - '8300:23333'
    restart: always
    working_dir: /app
    command: java  -server -jar  /app/app.jar
    volumes:
      - ./re:/app
  rule-login:
    container_name: rule-login
    environment:
      spring.redis.host: redis
      spring.redis.port: 6379
      spring.redis.password: youshallnotpass9
      spring.redis.database: 2
      auth.loginurl: http://43.135.220.141:8300/login/callback
      spring.datasource.url: jdbc:mysql://mysql57:3306/re?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&autoReconnect=true
      spring.datasource.username: root
      spring.datasource.password: 777888OP
      spring.datasource.hikari.connection-timeout: 5000
      spring.datasource.hikari.minimum-idle: 5
      spring.datasource.hikari.maximum-pool-size: 20
      spring.datasource.hikari.idle-timeout: 60000
      spring.datasource.hikari.pool-name: MysqlHikariCP
      spring.datasource.hikari.connection-test-query: SELECT 1
      spring.profiles.active: prod
      auth.appkey: e9d34b22cdcd11e78d73842b2b738d12
    image: adoptopenjdk/openjdk8
    ports:
      - '8301:23334'
    depends_on:
      - rule-engine
    working_dir: /app
    restart: always
    command: java -server -jar /app/app.jar
    volumes:
      - ./auth:/app


networks:
  default:
    name: fin
    external: true