version: '3'
services:
  rule-engine:
    container_name: rule-engine
    environment:
      spring.redis.host: r-t4nzs4kqupunhx9izmpd.redis.singapore.rds.aliyuncs.com
      spring.redis.port: 6379
      spring.redis.password: Aa123456
      spring.redis.database: 2
      jumei.auth.api.addr: http://8.219.49.205:8301/auth
      spring.datasource.url: jdbc:mysql://rm-t4ni526qb82jyhs247o.mysql.singapore.rds.aliyuncs.com:3306/risk_decision_engine?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&autoReconnect=true
      spring.datasource.username: decision_engine
      spring.datasource.password: cdMSQZq2zeg9
    image: adoptopenjdk/openjdk8
    ports:
      - '8300:23333'
    restart: always
    working_dir: /app
    network_mode: bridge
    command: java  -server -jar  /app/app.jar
    volumes:
      - /data/docker/rule/engine:/app
  rule-login:
    container_name: rule-login
    environment:
      spring.redis.host: r-t4nzs4kqupunhx9izmpd.redis.singapore.rds.aliyuncs.com
      spring.redis.port: 6379
      spring.redis.password: Aa123456
      spring.redis.database: 2
      auth.loginurl: http://8.219.49.205:8300/login/callback
      spring.datasource.url: jdbc:mysql://rm-t4ni526qb82jyhs247o.mysql.singapore.rds.aliyuncs.com:3306/risk_decision_engine?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&autoReconnect=true
      spring.datasource.username: decision_engine
      spring.datasource.password: cdMSQZq2zeg9
      spring.datasource.hikari.connection-timeout: 5000
      spring.datasource.hikari.minimum-idle: 5
      spring.datasource.hikari.maximum-pool-size: 20
      spring.datasource.hikari.idle-timeout: 60000
      spring.datasource.hikari.pool-name: MysqlHikariCP
      spring.datasource.hikari.connection-test-query: SELECT 1
      spring.profiles.active: prod
    network_mode: bridge
    image: adoptopenjdk/openjdk8
    ports:
      - '8301:23334'
    depends_on:
      - rule-engine
    working_dir: /app
    restart: always
    command: java -server -jar /app/app.jar
    volumes:
      - /data/docker/rule/auth:/app


# 加入已存在的网络
networks:
  default:
    external:
      name: my-custom-network